spring:
  application:
    name: plan-your-trip-bot

server:
  port: 8081

core-service:
  port: ${CORE_PORT:8180}
  rest-base-url: ${CORE_URL:http://localhost}:${core-service.port}

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

bot:
  username: plan_your_trip_bot
  token: ${BOT_TOKEN:}

http:
  client:
    pool:
      max-total: 100
      default-max-per-route: 150
    feignLoggerLevel: ${FEIGN_LOGGING_LEVEL:BASIC}

logging:
  level:
    com.planyourtrip.bot.service.core: ${FEIGN_LOGGING_LEVEL:debug}